acctmarket/applications/blog/urls.py
from django.urls import path

from acctmarket.applications.blog import views

app_name = "blog"
urlpatterns = [
    path(
        "create-post", views.CreateBlogPostView.as_view(),
        name="create_post"
    ),
    path(
        "create-category", views.CreateBlogCategory.as_view(),
        name="create_category"
    ),
    path(
        "edit-category/<slug:slug>/",
        views.EditPostCategoryView.as_view(),
        name="edit_category",
    ),  # noqa
    path(
        "delete-category/<slug:slug>/",
        views.DeletePostCategoryView.as_view(),
        name="delete_category",
    ),
    path(
        "create-list", views.CategoryListView.as_view(),
        name="category_list"
    ),
    path(
        "blog-list", views.BlogListView.as_view(),
        name="blog_list"
    ),
    path(
        "edit-blog/<slug:slug>/", views.BlogEditView.as_view(),
        name="edit_blog"
    ),
    path(
        "delete-blog/<slug:slug>/",
        views.BlogDeleteView.as_view(),
        name="delete_blog",
    ),
    path("", views.BlogViews.as_view(), name="blog_views"),
    path(
        "blog-detail/<slug:slug>/",
        views.BlogDetailView.as_view(),
        name="blog_detail",
    ),
    path(
        "create-banner", views.BannerCreateView.as_view(),
        name="banner_create"
    ),
    path(
        "list-banner", views.BannerListView.as_view(),
        name="list_banner"
    ),
    path(
        "edit-banner/<slug:slug>/",
        views.BannerEditView.as_view(),
        name="edit_banner",
    ),
    path(
        "delete-banner/<slug:slug>/",
        views.BannerDeleteView.as_view(),
        name="delete_banner",
    ),
]

acctmarket/applications/ecommerce/urls.py
from django.urls import path

from acctmarket.applications.ecommerce import views

app_name = "ecommerce"
urlpatterns = [
    path(
        "add-product", views.AddProductView.as_view(),
        name="add_product"
    ),
    path(
        "add-category", views.AddCategoryView.as_view(),
        name="add_category"
    ),
    path(
        "list-category", views.ListCategoryView.as_view(),
        name="list_category"
    ),
    path(
        "edit-category/<slug:pk>/",
        views.EditCategoryView.as_view(),
        name="edit_category",
    ),
    path(
        "delete-category/<slug:pk>/",
        views.DeleteCategoryView.as_view(),
        name="delete_category",
    ),
    path(
        "list-product", views.ListProductView.as_view(),
        name="list_product"
    ),
    path(
        "edit-product/<slug:pk>/",
        views.EditProductView.as_view(),
        name="edit_product",
    ),
    path(
        "delete-product/<slug:pk>/",
        views.DeleteProductView.as_view(),
        name="delete_product",
    ),
    path(
        "product-detail/<slug:pk>/",
        views.ProductDetailView.as_view(),
        name="product_detail",
    ),
    path(
        "create-product-image",
        views.ProductImagesCreateView.as_view(),
        name="create_product_image",
    ),
    path(
        "list-product-image",
        views.ListProductImages.as_view(),
        name="list_product_images",
    ),
    path(
        "update-product-image/<slug:pk>/",
        views.UpdateProductImages.as_view(),
        name="update_product_image",
    ),
    path(
        "delete-product-image/<slug:pk>/",
        views.DeleteProductImages.as_view(),
        name="delete_product_image",
    ),
    path(
        "product/<slug:pk>/add-review/",
        views.AddReviewsView.as_view(),
        name="add_review",
    ),
    path(
        "add-to-cart/", views.AddToCartView.as_view(),
        name="add_to_cart"
    ),
    path("cart", views.CartListView.as_view(), name="cart_list"),
    path(
        "delete-from-cart",
        views.DeleteFromCartView.as_view(),
        name="delete_from_cart_list",
    ),
    path(
        "update-to-cart",
        views.UpdateCartView.as_view(),
        name="delete_from_cart_list",
    ),

    path(
        "checkout", views.CheckoutView.as_view(),
        name="checkout"
    ),
    path(
        "proceed-payment", views.ProceedPayment.as_view(),
        name="proceed_payment"
    ),
    path(
        "payment-complete/",
        views.PaymentCompleteView.as_view(),
        name="payment_complete",
    ),
    path(
        "payment-failed",
        views.PaymentFailedView.as_view(),
        name="payment_failed",
    ),
    path(
        "wish-lists",
        views.WishlistListView.as_view(),
        name="wishlists",
    ),
    path(
        "add-to-wishlist",
        views.AddToWishlistView.as_view(),
        name="add_to_wishlist",
    ),
    path(
        "verify-payment/<str:reference>/",
        views.VerifyPaymentView.as_view(),
        name="verify_payment",
    ),
    path(
        "initiate-payment/<slug:order_id>/",
        views.InitiatePaystackPaymentView.as_view(),
        name="initiate_payment",
    ),
    path(
        "initiate-flutterwave-payment/<slug:order_id>/",
        views.InitiateFlutterwavePaymentView.as_view(),
        name="initiate_flutterwave_payment"

    ),
    path(
        "handle-flutter-wave-payment",
        views.HandleFlutterwavePaymentView.as_view(),
        name="handle_flutterwave_payment"
    ),
    path(
        "purchased-product",
        views.PurchasedProductsView.as_view(),
        name="purchased_products",
    ),
    path(
        "create_nowpayment/<slug:order_id>/",
        views.NowPaymentView.as_view(),
        name="create_nowpayment",
    ),
    path(
        "verify/nowpayment/<str:reference>/",
        views.VerifyNowPaymentView.as_view(),
        name="verify_nowpayment"
    ),
    path(
        "done-payment/<slug:order_id>/",
        views.DonePaymentView.as_view(),
        name="done_payment"
    ),
    path("ipn/", views.IPNView.as_view(), name="ipn"),


    # https://www.acctmarket.com/ecommerce/webhooks/flutterwave/
    path(
        "webhooks/flutterwave/",
        views.FlutterwaveWebhookView.as_view(),
        name="flutterwave_webhook"
        ),
    path(
         "wallet-payment/", views.WalletPaymentView.as_view(),
         name="wallet_payment"
        ),
    path(
            "apply-coupon/", views.ApplyCouponView.as_view(),
            name="apply_coupon"
        ),

]

acctmarket/applications/home/urls.py
from django.urls import path

from acctmarket.applications.home import views

app_name = "homeapp"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("shop", views.ProductShopListView.as_view(), name="shop_list"),
    path(
        "products/<slug:category_slug>/",
        views.ProductsCategoryList.as_view(),
        name="category_list",
    ),
    path(
        "product/<str:pk>/",
        views.ProductShopDetailView.as_view(),
        name="product_detail",
    ),
    path(
        "product-tags/<slug:tag_slug>/",
        views.ProductTagsList.as_view(),
        name="tag_list",
    ),
    path("search", views.ProductSearchView.as_view(),
         name="search"),
    path(
        "filter-product/", views.ProductFilterView.as_view(),
        name="filter_product"
    ),
    path(
        "dashboard", views.DashboardView.as_view(),
        name="dashboard"
    ),
    path(
        "order-details/<int:pk>/", views.OrderDetails.as_view(),
        name="order_details"
    ),
    path(
        "term-policy", views.TermsPolicy.as_view(),
        name="termspolicy"
    ),
    path(
        "contact-us", views.ContactPage.as_view(),
        name="contact_us"
    ),
    path(
        "contact-success", views.ContactSuccessPage.as_view(),
        name="contact_success"
    )
]

acctmarket/applications/refer/urls.py
from django.urls import path

from acctmarket.applications.refer.views import (FlutterWalletFundView,
                                                 FlutterwaveCallbackView,
                                                 MarkAllNotificationsReadView,
                                                 NotificationListView,
                                                 NowPaymentCallbackView,
                                                 NowPaymentWalletFundView,
                                                 ReferralListView,
                                                 SMSCampaignCreateView,
                                                 SMSCampaignDetailView,
                                                 SMSCampaignListView,
                                                 SMSCampaignSendView,
                                                 SMSCampaignUpdateView,
                                                 WalletDetailView,
                                                 WalletFundingCancelView,
                                                 WalletFundingSuccessView,
                                                 WalletTrasactionListViews)

app_name = "referals"
urlpatterns = [
    path("", ReferralListView.as_view(), name="referals_list"),
    path(
        "my-wallet",
        WalletDetailView.as_view(), name="walet_detail"
    ),
    path(
        "fund-wallet/now-payment",
        NowPaymentWalletFundView.as_view(), name="fund_wallet"
    ),
    path(
        "fund-wallets/flutter-wave",
        FlutterWalletFundView.as_view(), name="fund_wallet2"
    ),
    path(
        "wallet/funding-callback/",
        FlutterwaveCallbackView.as_view(), name="flutterwave_callback"
    ),
    path(
        "wallet/nowpayment-callback",
        NowPaymentCallbackView.as_view(),
        name="nowpayment_callback"
    ),
    path(
        "funding-success/",
        WalletFundingSuccessView.as_view(), name="funding_success"
    ),
    path(
        "funding-cancel/",
        WalletFundingCancelView.as_view(), name="funding_cancel"
    ),
    path(
        "transactions/", WalletTrasactionListViews.as_view(),
        name="wallet_transaction_list"
    ),
    path(
        "notifications/", NotificationListView.as_view(),
        name="notifications"
    ),
    path(
        "notifications/mark-all-read/",
        MarkAllNotificationsReadView.as_view(),
        name="mark_all_notifications_read"
    ),
    path(
        "campaigns/", SMSCampaignListView.as_view(),
        name="sms_campaign_list"
    ),
    path(
        "campaigns/<int:pk>/", SMSCampaignDetailView.as_view(),
        name="sms_campaign_detail"
    ),
    path(
        "campaigns/create/", SMSCampaignCreateView.as_view(),
        name="sms_campaign_create"
    ),
    path(
        "campaigns/<int:pk>/update/", SMSCampaignUpdateView.as_view(),
        name="sms_campaign_update"
    ),
    path(
        "campaigns/<int:pk>/send/", SMSCampaignSendView.as_view(),
        name="sms_campaign_send"
    ),
]

acctmarket/applications/support/urls.py
from django.urls import path

from acctmarket.applications.support.views import (CreateFAQ, DeleteFAQViews,
                                                   EditFAQViews, FAQListView,
                                                   HELPOrFAQPage,
                                                   TicketDetailView,
                                                   TicketListView)

app_name = "support"
urlpatterns = [
    path("tickets", TicketListView.as_view(), name="ticket_list"),
    path("<int:pk>/", TicketDetailView.as_view(), name="ticket_detail"),
    path("create-faq", CreateFAQ.as_view(), name="create_faq"),
    path("edit-faq/<int:pk>/", EditFAQViews.as_view(), name="edit_faq"),
    path("delete-faq/<int:pk>/", DeleteFAQViews.as_view(), name="delete_faq"),
    path("faq-list", FAQListView.as_view(), name="faq_list"),
    path("help", HELPOrFAQPage.as_view(), name="helppage"),
]

acctmarket/applications/users/urls.py
from django.urls import path

from acctmarket.applications.users.views import (accountant_account,
                                                 administrator_account,
                                                 content_manager_account,
                                                 content_manager_dashboard,
                                                 customer_dashboard,
                                                 customer_support_reps,
                                                 customers_account,
                                                 dashboard_view, resend_otp,
                                                 superuser, user_detail_view,
                                                 user_redirect_view,
                                                 user_update_view, verify_otp)

app_name = "users"
urlpatterns = [
    path(
        "signup/adminstrator-signup",
        view=administrator_account,
        name="administrator_account",
    ),
    path(
        "signup/content-manager",
        view=content_manager_account,
        name="content_manager_account",
    ),
    path(
        "signup/accountant", view=accountant_account,
        name="accountant_account"),
    path(
        "signup/customer-support",
        view=customer_support_reps,
        name="customer_support_reps",
    ),
    path("signup/customer", view=customers_account, name="customers_account"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
    path("signup/superuser", view=superuser, name="superuser"),

    path("dashboard", view=dashboard_view, name="dashboard_view"),
    path(
        "dashboard/customer",
        view=customer_dashboard,
        name="customer_dashboard"
    ),
    path(
        "dashboard/content-manager",
        view=content_manager_dashboard,
        name="content_manager_dashboard"
    ),

    path(
        "verify-otp/<slug:user_id>/",
        view=verify_otp, name="verify_otp"
    ),
    path("resend-otp/<slug:user_id>/", view=resend_otp, name="resend_otp"),




]

config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/", include(
            "acctmarket.applications.users.urls", namespace="users"
        )
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    #  ecomercce manaement
    path(
        "ecommerce/",
        include(
            "acctmarket.applications.ecommerce.urls", namespace="ecommerce"
        ),
    ),
    # support management
    path(
        "support/",
        include("acctmarket.applications.support.urls", namespace="support"),
    ),
    path("blog/", include(
        "acctmarket.applications.blog.urls", namespace="blog")
    ),
    path("", include(
        "acctmarket.applications.home.urls", namespace="homeapp")
    ),
    # referal management
    path(
        "referal/", include(
            "acctmarket.applications.refer.urls", namespace="refer"
        )
    ),

    path("ckeditor/", include("ckeditor_uploader.urls")),

    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns  # noqa

acctmarket/applications/home/models.py
# Create your models here.

acctmarket/applications/home/forms.py
from django.forms import EmailInput, ModelForm, Textarea, TextInput

from acctmarket.applications.support.models import ContactUs


class ContactForm(ModelForm):
    class Meta:
        model = ContactUs
        fields = [
            "name", "email",
            "subject", "message"
        ]

        widgets = {
            "name": TextInput(attrs={
                # "class": "form-control",
                "placeholder": "Enter your Name",
            }),

            "email": EmailInput(attrs={
                # "class": "form-control",
                "placeholder": "Enter your Email",
            }),

            "subject": TextInput(attrs={
                # "class": "form-control",
                "placeholder": "Enter your Subject",
            }),

            "message": Textarea(attrs={
                # "class": "form-control",
                "placeholder": "Enter your Message",
                "rows": 5
            }),
        }

acctmarket/applications/refer/forms.py
from django import forms


class WalletFundingForm(forms.Form):
    amount = forms.DecimalField(
        max_digits=10,
        decimal_places=2,
        min_value=0.01,  # Ensures only positive values
        label="Amount to Add",
        widget=forms.NumberInput(attrs={
            "placeholder": "$120",
            "class": "crancy__item-input"
        })
    )

acctmarket/templates/partials/_blog_sidebar.html
<div class="sidebar">
  <div class="vertical-menu">
    <ul>
      {% for cats in blog_categories %}
        <li>
          <a href="#">{{ cats.title }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <!--latest-products-->
  <div class="products-list mt-30">
    <div class="section-title mb-30">
      <h3>Latest Items</h3>
    </div>
    <div class="one-carousel dots-none">
      <div>
        <ul class="list-none">
          {% for product in just_arrived|slice:"5" %}
            <li>
              <div class="product-single style-2">
                <div class="row align-items-center m-0">
                  <div class="col-lg-4 p-0">
                    <div class="product-thumb">
                      <a href="#">
                        <img src="{{ product.image.url }}" alt="" />
                      </a>
                    </div>
                  </div>
                  <div class="col-lg-8 p-0">
                    <div class="product-title">
                      <h4>
                        <a href="{% url 'homeapp:product_detail' product.pk %} ">{{ product.title }}</a>
                      </h4>
                    </div>
                    <div class="product-price-rating">
                      <span>${{ product.price }}</span>
                      <del>${{ product.oldprice }}</del>
                    </div>
                  </div>
                </div>
              </div>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>

acctmarket/templates/partials/_header.html
{% load static %}

<!--header-area start-->
<header class="header-area">
  <div class="desktop-header">
    <!--header-top-->
    <div class="header-top">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-6">
            <div class="topbar-left"></div>
          </div>
          <div class="col-lg-6">
            <div class="topbar-right">
              <div class="register-login style-2 pull-right">
                {% if request.user.is_authenticated %}
                  <a href="{% url 'users:dashboard_view' %}">Dashboard</a>
                  {% comment %} <a href="{% url 'users:detail' request.user.pk %}">profile</a> {% endcomment %}
                  <span>/</span>
                  <a href="{% url 'ecommerce:purchased_products' %}">Purchased Products</a>
                  <span>/</span>
                  <a href="{% url 'account_logout' %}">Signout</a>
                {% else %}
                  {% if ACCOUNT_ALLOW_REGISTRATION %}
                    <a href="{% url 'users:customers_account' %}">Signup</a>
                  {% endif %}
                  <span>/</span>
                  <a href="{% url 'account_login' %}">Signin</a>
                {% endif %}
              </div>
              <div class="currency-bar pull-right">
                <ul>
                  <li>
                    <a href="{% url 'support:helppage' %}">FAQs <i class="fa fa-angle-down"></i></a>
                    {% comment %} <ul>
                      <li>
                        <a href="#">EUR</a>
                      </li>
                      <li>
                        <a href="#">AUD</a>
                      </li>
                    </ul> {% endcomment %}
                  </li>
                  <li>
                    <span>|</span>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--header-bottom-->
    <div class="header-bottom">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-3">
            <div class="logo">
              <a href="{% url 'homeapp:home' %}">
                <img src="{% static 'assets/images/logos/logo.png' %}" alt="logo" />
              </a>
            </div>
          </div>
          <div class="col-lg-6">
            <form method="Get"
                  action="{% url 'homeapp:search' %}"
                  class="search-box style-2">
              <select>
                <option>All Categories</option>
                {% for cats in top_categories %}
                  <option>
                    <a href="homeapp:category_list" cats.slug>{{ cats.title }}</a>
                  </option>
                {% endfor %}
              </select>
              <input type="text" name="q" placeholder="What do you need?" />
              <button type="submit">Search</button>
            </form>
          </div>
          <div class="col-lg-3">
            <div class="mini-cart pull-right">
              <ul>
                {% comment %} <li>
                  <a href="#" title="Track Your Order"><i class="ti-truck"></i></a>
                </li> {% endcomment %}
                <li>
                  <a href="{% url 'ecommerce:wishlists' %}"><i class="icon_heart_alt"></i><span>{{ wishlist.count }}</span></a>
                </li>
                <li>
                  <a href="{% url 'ecommerce:cart_list' %}" class="minicart-icon"><i class="icon_bag_alt"></i><span class="cart-item-count">{{ request.session.cart_data_obj|length }}</span></a>
                  {% comment %} <a href="javascript:void(0);" class="minicart-icon"><i class="icon_bag_alt"></i><span class="cart-item-count">{{ request.session.cart_data_obj|length }}</span></a> {% endcomment %}
                  {% comment %} <div class="cart-dropdown">
                    <div class="mini-cart-checkout">
                      <a href="{% url 'ecommerce:cart_list' %}" class="btn-common view-cart">VIEW CART</a>
                      <a href="{% url 'ecommerce:checkout' %}" class="btn-common checkout mt-10">CHECK OUT</a>
                    </div>
                  </div> {% endcomment %}
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% include 'partials/_mobile_header.html' %}
</header>
<!--header-area end-->

acctmarket/templates/partials/_mobile_header.html
{% load static %}

<!--mobile-header-->
<div class="sticker mobile-header">
  <div class="container">
    <!--logo and cart-->
    <div class="row align-items-center">
      <div class="col-sm-4 col-6">
        <div class="logo">
          <a href="{% url 'homeapp:home' %}">
            <img src="{% static 'assets/images/logos/logo.png' %}" alt="logo" />
          </a>
        </div>
      </div>
      <div class="col-sm-8 col-6">
        <div class="mini-cart text-right">
          <ul>
            <li>
              <a href="{% url 'ecommerce:wishlists' %}"><i class="icon_heart_alt"></i><span>{{ wishlist.count }}</span></a>
            </li>
            <li class="minicart-icon">
              <a href="#"><i class="icon_bag_alt"></i><span class="cart-item-count">{{ request.session.cart_data_obj|length }}</span></a>
              <div class="cart-dropdown">
                <div class="mini-cart-checkout">
                  <a href="{% url 'ecommerce:cart_list' %}" class="btn-common view-cart">VIEW CART</a>
                  <a href="{% url 'ecommerce:checkout' %}"
                     class="btn-common checkout mt-10">CHECK OUT</a>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <!--search-box-->
    <div class="row align-items-center">
      <div class="col-sm-12">
        <form method="Get"
              action="{% url 'homeapp:search' %}"
              class="search-box mt-sm-15">
          <select>
            <option>All Categories</option>
            {% for cats in top_categories %}
              <option>
                <a href="">{{ cats.title }}</a>
              </option>
            {% endfor %}
          </select>
          <input type="text" name="q" placeholder="What do you need?" />
          <button>Search</button>
        </form>
      </div>
    </div>
    <!--site-menu-->
    <div class="row mt-sm-10">
      <div class="col-lg-12">
        <a href="#my-menu" class="mmenu-icon pull-left"><i class="fa fa-bars"></i></a>
        <div class="mainmenu">
          <nav id="my-menu">
            <ul>
              <li>
                <a href="{% url 'homeapp:home' %}">Home</a>
              </li>
              <li>
                <a href="{% url 'homeapp:shop_list' %}">
                  <span class="text-label label-featured"></span>
                  Shop
                </a>
              </li>
              <li>
                <a href="{% url 'blog:blog_views' %}">Blog</a>
              </li>
              <li>
                <a href="{% url 'homeapp:contact_us' %}">Contact</a>
              </li>
              {% if request.user.is_authenticated %}
                <li>
                  <a href="#">User</a>
                  <ul class="submenu">
                    <li>
                      <a href="{% url 'users:dashboard_view' %}">Dashboard</a>
                    </li>
                    <li>
                      <a href="{% url 'ecommerce:purchased_products' %}">Purchased Product</a>
                      <a href="{% url 'account_logout' %}">Signout</a>
                    </li>
                  </ul>
                </li>
              {% else %}
                <li>
                  <a href="#">User <b class="caret"></b></a>
                  <ul class="submenu">
                    {% if ACCOUNT_ALLOW_REGISTRATION %}
                      <li>
                        <a href="{% url 'users:customers_account' %}">Signup</a>
                      </li>
                    {% endif %}
                    <li>
                      <a href="{% url 'account_login' %}">Signin</a>
                    </li>
                  </ul>
                </li>
              {% endif %}
            </ul>
          </nav>
        </div>
        <!--category-->
        <div class="collapse-menu mt-0 pull-right">
          <ul>
            <li>
              <a class="vm-menu"><i class="fa fa-navicon"></i><span>All
              Categories <b class="caret"></b></span></a>
              <ul class="vm-dropdown">
                {% for category in top_categories %}
                  {% if not category.sub_category %}
                    <li>
                      <div style="display: flex; align-items: center;">
                        <a href="{% url 'homeapp:category_list' category_slug=category.slug %}"
                           style="text-decoration"
                           :none>
                          <img height="25" width="25" src="{{ category.image.url }}" alt="" />
                          <span>{{ category.title }}</span>
                        </a>
                        {% if category.subcategories.exists %}<b class="caret" style="margin-left: 5px;"></b>{% endif %}
                      </div>
                      {% if category.subcategories.exists %}
                        <ul class="mega-menu" style="margin-left:  25px;">
                          {% for subcategory in category.subcategories.all %}
                            <li class="megamenu-single" style="display: flex; align-items: center;">
                              <a href="{% url 'homeapp:category_list' category_slug=subcategory.slug %}"
                                 style="text-decoration"
                                 :none>
                                <span class="mega-menu-title">{{ subcategory.title }}</span>
                              </a>
                              {% if subcategory.subcategories.exists %}
                                <ul style="margin-left:  25px;">
                                  {% for sub_subcategory in subcategory.subcategories.all %}
                                    <li>
                                      <a href="{% url 'homeapp:category_list' category_slug=sub_subcategory.slug %}"
                                         style="text-decoration"
                                         :none>{{ sub_subcategory.title }}</a>
                                    </li>
                                  {% endfor %}
                                </ul>
                              {% endif %}
                            </li>
                          {% endfor %}
                        </ul>
                      {% endif %}
                    </li>
                  {% endif %}
                {% endfor %}
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

acctmarket/templates/partials/_shop_pagianations.html
<div class="row align-items-center mt-30">
  <div class="col-lg-6">
    <div class="site-pagination">
      <ul>
        {% if page_obj.has_previous %}
          <li>
            <a href="?page=1"><i class="fa fa-long-arrow-left"></i></a>
          </li>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
          {% if num == page_obj.number %}
            <li>
              <a href="#" class="active">{{ num }}</a>
            </li>
          {% else %}
            <li>
              <a href="?page={{ num }}" class="active">{{ num }}</a>
            </li>
          {% endif %}
        {% endfor %}
        <li>of</li>
        <li>
          <a href="#">{{ page_obj.end_index }}</a>
        </li>
        {% if page_obj.has_next %}
          <li>
            <a href="?page={{ page_obj.paginator.num_pages }}"><i class="fa fa-long-arrow-right"></i></a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>