acctmarket/applications/blog/urls.py
from django.urls import path

from acctmarket.applications.blog import views

app_name = "blog"
urlpatterns = [
    path(
        "create-post", views.CreateBlogPostView.as_view(),
        name="create_post"
    ),
    path(
        "create-category", views.CreateBlogCategory.as_view(),
        name="create_category"
    ),
    path(
        "edit-category/<slug:slug>/",
        views.EditPostCategoryView.as_view(),
        name="edit_category",
    ),  # noqa
    path(
        "delete-category/<slug:slug>/",
        views.DeletePostCategoryView.as_view(),
        name="delete_category",
    ),
    path(
        "create-list", views.CategoryListView.as_view(),
        name="category_list"
    ),
    path(
        "blog-list", views.BlogListView.as_view(),
        name="blog_list"
    ),
    path(
        "edit-blog/<slug:slug>/", views.BlogEditView.as_view(),
        name="edit_blog"
    ),
    path(
        "delete-blog/<slug:slug>/",
        views.BlogDeleteView.as_view(),
        name="delete_blog",
    ),
    path("", views.BlogViews.as_view(), name="blog_views"),
    path(
        "blog-detail/<slug:slug>/",
        views.BlogDetailView.as_view(),
        name="blog_detail",
    ),
    path(
        "create-banner", views.BannerCreateView.as_view(),
        name="banner_create"
    ),
    path(
        "list-banner", views.BannerListView.as_view(),
        name="list_banner"
    ),
    path(
        "edit-banner/<slug:slug>/",
        views.BannerEditView.as_view(),
        name="edit_banner",
    ),
    path(
        "delete-banner/<slug:slug>/",
        views.BannerDeleteView.as_view(),
        name="delete_banner",
    ),
]

acctmarket/applications/home/urls.py
from django.urls import path

from acctmarket.applications.home import views

app_name = "homeapp"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("shop", views.ProductShopListView.as_view(), name="shop_list"),
    path(
        "products/<slug:category_slug>/",
        views.ProductsCategoryList.as_view(),
        name="category_list",
    ),
    path(
        "product/<str:pk>/",
        views.ProductShopDetailView.as_view(),
        name="product_detail",
    ),
    path(
        "product-tags/<slug:tag_slug>/",
        views.ProductTagsList.as_view(),
        name="tag_list",
    ),
    path("search", views.ProductSearchView.as_view(),
         name="search"),
    path(
        "filter-product/", views.ProductFilterView.as_view(),
        name="filter_product"
    ),
    path(
        "dashboard", views.DashboardView.as_view(),
        name="dashboard"
    ),
    path(
        "order-details/<int:pk>/", views.OrderDetails.as_view(),
        name="order_details"
    ),
    path(
        "term-policy", views.TermsPolicy.as_view(),
        name="termspolicy"
    ),
    path(
        "contact-us", views.ContactPage.as_view(),
        name="contact_us"
    ),
    path(
        "contact-success", views.ContactSuccessPage.as_view(),
        name="contact_success"
    )
]

acctmarket/applications/refer/urls.py
from django.urls import path

from acctmarket.applications.refer.views import (FlutterWalletFundView,
                                                 FlutterwaveCallbackView,
                                                 MarkAllNotificationsReadView,
                                                 NotificationListView,
                                                 NowPaymentCallbackView,
                                                 NowPaymentWalletFundView,
                                                 ReferralListView,
                                                 SMSCampaignCreateView,
                                                 SMSCampaignDetailView,
                                                 SMSCampaignListView,
                                                 SMSCampaignSendView,
                                                 SMSCampaignUpdateView,
                                                 WalletDetailView,
                                                 WalletFundingCancelView,
                                                 WalletFundingSuccessView,
                                                 WalletTrasactionListViews)

app_name = "referals"
urlpatterns = [
    path("", ReferralListView.as_view(), name="referals_list"),
    path(
        "my-wallet",
        WalletDetailView.as_view(), name="walet_detail"
    ),
    path(
        "fund-wallet/now-payment",
        NowPaymentWalletFundView.as_view(), name="fund_wallet"
    ),
    path(
        "fund-wallets/flutter-wave",
        FlutterWalletFundView.as_view(), name="fund_wallet2"
    ),
    path(
        "wallet/funding-callback/",
        FlutterwaveCallbackView.as_view(), name="flutterwave_callback"
    ),
    path(
        "wallet/nowpayment-callback",
        NowPaymentCallbackView.as_view(),
        name="nowpayment_callback"
    ),
    path(
        "funding-success/",
        WalletFundingSuccessView.as_view(), name="funding_success"
    ),
    path(
        "funding-cancel/",
        WalletFundingCancelView.as_view(), name="funding_cancel"
    ),
    path(
        "transactions/", WalletTrasactionListViews.as_view(),
        name="wallet_transaction_list"
    ),
    path(
        "notifications/", NotificationListView.as_view(),
        name="notifications"
    ),
    path(
        "notifications/mark-all-read/",
        MarkAllNotificationsReadView.as_view(),
        name="mark_all_notifications_read"
    ),
    path(
        "campaigns/", SMSCampaignListView.as_view(),
        name="sms_campaign_list"
    ),
    path(
        "campaigns/<int:pk>/", SMSCampaignDetailView.as_view(),
        name="sms_campaign_detail"
    ),
    path(
        "campaigns/create/", SMSCampaignCreateView.as_view(),
        name="sms_campaign_create"
    ),
    path(
        "campaigns/<int:pk>/update/", SMSCampaignUpdateView.as_view(),
        name="sms_campaign_update"
    ),
    path(
        "campaigns/<int:pk>/send/", SMSCampaignSendView.as_view(),
        name="sms_campaign_send"
    ),
]

config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/", include(
            "acctmarket.applications.users.urls", namespace="users"
        )
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    #  ecomercce manaement
    path(
        "ecommerce/",
        include(
            "acctmarket.applications.ecommerce.urls", namespace="ecommerce"
        ),
    ),
    # support management
    path(
        "support/",
        include("acctmarket.applications.support.urls", namespace="support"),
    ),
    path("blog/", include(
        "acctmarket.applications.blog.urls", namespace="blog")
    ),
    path("", include(
        "acctmarket.applications.home.urls", namespace="homeapp")
    ),
    # referal management
    path(
        "referal/", include(
            "acctmarket.applications.refer.urls", namespace="refer"
        )
    ),

    path("ckeditor/", include("ckeditor_uploader.urls")),

    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns  # noqa

acctmarket/applications/home/models.py
# Create your models here.

acctmarket/applications/blog/forms.py
from ckeditor.widgets import CKEditorWidget
from django.forms import FileInput, ModelForm, Select, TextInput

from acctmarket.applications.blog.models import Banner, BlogCategory, Post


class BlogCategoryForm(ModelForm):
    class Meta:
        model = BlogCategory
        fields = [
            "title",
            "image",
            "sub_category",
        ]

        widgets = {
            "title": TextInput(
                attrs={"class": "form-control", "placeholder": "Enter  title"},
            ),
            "image": FileInput(
                attrs={"class": "form-control", "name": "filename"}
            ),
            "sub_category": Select(attrs={"class": "form-control"}),
        }


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            "title",
            "image",
            "content",
            "category",
            "tags",
        ]

        widgets = {
            "title": TextInput(
                attrs={
                    "class": "form-control", "placeholder": "Enter post title"
                },
            ),
            "image": FileInput(attrs={
                "class": "form-control", "name": "filename"
            }),
            "content": CKEditorWidget(
                attrs={
                    "class": "form-control",
                    "placeholder": "Enter post content"
                },
            ),
            "category": Select(attrs={"class": "form-control"}),
            "tags": TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Enter tags separate each by comma",
                },
            ),
        }


class BannerForm(ModelForm):
    class Meta:
        model = Banner
        fields = [
            "title",
            "sub_title",
            "image",
            "featured_category",
            "featured_product",
        ]

        widgets = {
            "title": TextInput(
                attrs={
                    "class": "form-control", "placeholder": "Enter short title"
                },
            ),
            "sub_title": TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Enter very short description",
                },
            ),
            "featured_category": Select(attrs={"class": "form-control"}),
            "featured_product": Select(attrs={"class": "form-control"}),
            "image": FileInput(attrs={
                "class": "form-control", "name": "filename"
            }),
        }

acctmarket/applications/blog/views.py
from django.db.models import Count
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from acctmarket.applications.blog.forms import (Banner, BannerForm,
                                                BlogCategory, BlogCategoryForm,
                                                Post, PostForm)
from acctmarket.utils.mixins import ContentManagerRequiredMixin

# Create your views here.


class SlugMixin:
    slug_field = "slug"
    slug_url_kwarg = "slug"

    def get_object(self, queryset=None):
        """
        Retrieves an object from the queryset based on the provided slug.

        Parameters:
            queryset (QuerySet, optional): The queryset to filter the objects.
            If not provided, the default queryset is used.

        Returns:
            object: The object with the matching slug.
            If no object is found, a Http404 exception is raised.
        """
        if queryset is None:
            queryset = self.get_queryset()
        slug = self.kwargs.get(self.slug_url_kwarg)
        queryset = queryset.filter(**{self.slug_field: slug})
        return get_object_or_404(queryset)


class CreateBlogCategory(ContentManagerRequiredMixin, CreateView):
    model = BlogCategory
    form_class = BlogCategoryForm
    template_name = "pages/blog/create_blog_category.html"
    success_url = reverse_lazy("blog:category_list")


class CategoryListView(ContentManagerRequiredMixin, ListView):
    model = BlogCategory
    template_name = "pages/blog/category_list.html"
    paginate_by = 10

    def get_queryset(self):
        return BlogCategory.objects.annotate(
            total_products=Count("post")).order_by(
                "-created_at",
        )


class EditPostCategoryView(
    ContentManagerRequiredMixin, SlugMixin, UpdateView
):
    model = BlogCategory
    form_class = BlogCategoryForm
    template_name = "pages/blog/create_blog_category.html"
    success_url = reverse_lazy("blog:category_list")


class DeletePostCategoryView(
    ContentManagerRequiredMixin, SlugMixin, DeleteView
):
    model = BlogCategory
    template_name = "pages/blog/confirm_delete.html"
    success_url = reverse_lazy("blog:category_list")


# =======================================  Blog Categories ends here


class CreateBlogPostView(ContentManagerRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = "pages/blog/create_blog_post.html"
    success_url = reverse_lazy("blog:blog_list")


class BlogListView(ContentManagerRequiredMixin, ListView):
    model = Post
    paginate_by = 10
    template_name = "pages/blog/blog_list.html"

    def get_queryset(self):
        return Post.objects.all().order_by("-created_at")


class BlogEditView(ContentManagerRequiredMixin, SlugMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = "pages/blog/create_blog_post.html"
    success_url = reverse_lazy("blog:blog_list")


class BlogDeleteView(ContentManagerRequiredMixin, SlugMixin, DeleteView):
    model = Post
    template_name = "pages/blog/delete_blog.html"
    success_url = reverse_lazy("blog:blog_list")


class BlogViews(ListView):
    model = Post
    template_name = "pages/blog/blog_views.html"
    context_object_name = "blog_posts"
    paginate_by = 5

    def get_queryset(self):
        return Post.objects.all().order_by("-created_at")


class BlogDetailView(DetailView):
    model = Post
    template_name = "pages/blog/blog_details.html"
    context_object_name = "blog_post"
    slug_field = "slug"
    slug_url_kwarg = "slug"


# =======================================  End if blog section


class BannerCreateView(ContentManagerRequiredMixin, CreateView):
    model = Banner
    form_class = BannerForm
    template_name = "pages/blog/create_home_banner.html"
    success_url = reverse_lazy("blog:list_banner")


class BannerEditView(ContentManagerRequiredMixin, SlugMixin, UpdateView):
    model = Banner
    form_class = BannerForm
    template_name = "pages/blog/create_home_banner.html"
    success_url = reverse_lazy("blog:list_banner")


class BannerDeleteView(ContentManagerRequiredMixin, SlugMixin, DeleteView):
    model = Banner
    template_name = "pages/blog/delete_banner.html"
    success_url = reverse_lazy("blog:list_banner")


class BannerListView(ContentManagerRequiredMixin, ListView):
    model = Banner
    paginate_by = 10
    template_name = "pages/blog/banner_list.html"
    context_object_name = "banners"

acctmarket/applications/support/views.py
# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from acctmarket.applications.support.forms import FAQForm, ResponseForm
from acctmarket.applications.support.models import FrequestAskQuestion, Ticket
from acctmarket.utils.mixins import CustomerSupportRepresentativemixin

# Create your views here.


class CreateFAQ(CustomerSupportRepresentativemixin, CreateView):
    model = FrequestAskQuestion
    form_class = FAQForm
    template_name = "pages/support/create_faq.html"
    success_url = reverse_lazy("support:faq_list")


class FAQListView(CustomerSupportRepresentativemixin, ListView):
    model = FrequestAskQuestion
    template_name = "pages/support/faq_list.html"
    context_object_name = "faqs"


class EditFAQViews(CustomerSupportRepresentativemixin, UpdateView):
    model = FrequestAskQuestion
    form_class = FAQForm
    template_name = "pages/support/create_faq.html"


class DeleteFAQViews(CustomerSupportRepresentativemixin, DeleteView):
    model = FrequestAskQuestion
    template_name = "pages/support/faq_delete.html"
    form_class = FAQForm
    success_url = reverse_lazy("support:faq_list")
    context_object_name = "faq"


class HELPOrFAQPage(ListView):
    model = FrequestAskQuestion
    template_name = "pages/support/help_or_faqpage.html"
    context_object_name = "faqs"


class TicketDetailView(LoginRequiredMixin, DetailView):
    model = Ticket
    template_name = "pages/support/ticket_detail.html"
    context_object_name = "ticket"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = ResponseForm()
        return context


class TicketListView(CustomerSupportRepresentativemixin, ListView):
    model = Ticket
    template_name = "pages/support/ticket_list.html"
    context_object_name = "tickets"

    def get_queryset(self):
        return Ticket.objects.filter(customer=self.request.user)

acctmarket/templates/pages/refer/flutterfund_wallet.html
{% extends 'dashboardbase.html' %}

{% load static %}

{% block content %}
  <!-- crancy Dashboard -->
  <section class="crancy-adashboard crancy-show">
    <div class="container container__bscreen">
      <div class="row">
        <div class="col-xxl-8 col-12 crancy-main__column">
          <div class="crancy-body">
            <!-- Dashboard Inner -->
            <div class="crancy-dsinner">
              <form method="post" action="{% url 'referals:fund_wallet2' %}">
                {% csrf_token %}
                <div class="row">
                  <div class="container">
                    <div class="row justify-content-center">
                      <div class="col-lg-6 col-md-8 col-sm-10 col-12 mg-top-30">
                        <!-- Product Card -->
                        <div class="crancy-product-card">
                          <h4 class="crancy-product-card__title">
                            Fund Wallet with Flutterwave.
                            <a href="#">
                              <img src="{% static 'dashboard/img/alert-circle.svg' %}" alt="Info" />
                            </a>
                          </h4>
                          {% include 'partials/_messages.html' %}
                          <div class="crancy__item-form--group mg-top-25">
                            <label class="crancy__item-label crancy__item-label-product">Enter Amount</label>
                            <input type="number"
                                   name="amount"
                                   id="amount"
                                   class="form-control"
                                   required
                                   min="1"
                                   placeholder="$120" />
                          </div>
                          <br />
                          <button type="submit" class="btn btn-outline-primary">Fund Wallet</button>
                        </div>
                        <!-- End Product Card -->
                      </div>
                    </div>
                  </div>
                </div>
              </form>
            </div>
            <!-- End Dashboard Inner -->
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End crancy Dashboard -->
</div>
{% endblock content %}
{% comment %} {% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <h2>Fund Your Wallet</h2>
    <p>Add funds to your wallet securely using Flutterwave.</p>

    <form method="post" action="{% url 'referals:fund_wallet2' %}">
        {% csrf_token %}

        <div class="form-group">
            <label for="amount">Amount (NGN):</label>
            <input type="number" name="amount" id="amount" class="form-control" required min="1" placeholder="Enter amount" />
        </div>

        <button type="submit" class="btn btn-primary mt-3">Fund Wallet</button>
    </form>
</div>
{% endblock %} {% endcomment %}

acctmarket/templates/pages/refer/funding_success.html
{% extends "base.html" %}

{% block content %}
  <div class="container my-5">
    <div class="row justify-content-center">
      {% include 'partials/_messages.html' %}
      <div class="col-md-8 col-lg-6 text-center">
        <!-- Success Icon and Alert -->
        <div class="alert alert-success p-4"
             role="alert"
             style="border-radius: 10px">
          <div class="display-4 mb-3">
            <i class="bi bi-check-circle-fill"></i>
          </div>
          <h4 class="alert-heading mb-3">Wallet Funded Successfully!</h4>
          <p class="lead">Your wallet balance has been updated, and the funds are now available for use.</p>
          <hr />
          <p class="small text-muted">You can review your balance and recent transactions in your wallet.</p>
        </div>
        <!-- Action Buttons -->
        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
          <a href="{% url 'referals:walet_detail' %}"
             class="btn btn-outline-primary btn-lg me-2"
             data-bs-toggle="tooltip"
             title="View your updated wallet balance">View Wallet</a>  &nbsp;&nbsp;
          <a href="{% url 'homeapp:home' %}"
             class="btn btn-outline-secondary btn-lg"
             data-bs-toggle="tooltip"
             title="Return to the homepage">Back to Home</a>
        </div>
      </div>
    </div>
  </div>
  <script>
    // Initialize Bootstrap tooltips
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
    var tooltipList = tooltipTriggerList.map(function(tooltipTriggerEl) {
      return new bootstrap.Tooltip(tooltipTriggerEl);
    });
  </script>
{% endblock %}

acctmarket/templates/pages/refer/notification_list.html
{% extends 'dashboardbase.html' %}

{% load static %}

{% block content %}
  <!-- crancy Dashboard -->
  <section class="crancy-adashboard crancy-show">
    <div class="container container__bscreen">
      <div class="row">
        <div class="col-xxl-8 col-12 crancy-main__column">
          <div class="crancy-body">
            <!-- Dashboard Inner -->
            <div class="crancy-dsinner">
              <div class="crancy-table crancy-table--v3 mg-top-30">
                {% if unread_count != 0 %}
                  <button id="mark-all-read" class="btn btn-primary">Messages ({{ unread_count }}) Mark All as Read</button>
                {% endif %}
                {% if not notifications %}
                  <h3>No Notifications yet...</h3>
                {% else %}
                  <table id="crancy-table__main"
                         class="crancy-table__main crancy-table__main-v3">
                    <!-- crancy Table Head -->
                    <thead class="crancy-table__head">
                      <tr>
                        <th class="crancy-table__column-1 crancy-table__h1">
                          <div class="crancy-wc__checkbox">
                            <input class="crancy-wc__form-check"
                                   id="checkbox"
                                   name="checkbox"
                                   type="checkbox" />
                            <span>Notification for</span>
                          </div>
                        </th>
                        <th class="crancy-table__column-2 crancy-table__h2">Date</th>
                        <th class="crancy-table__column-3 crancy-table__h3">Message</th>
                      </tr>
                    </thead>
                    <!-- crancy Table Body -->
                    <tbody class="crancy-table__body">
                      {% for notification in notifications %}
                        <tr>
                          <td class="crancy-table__column-5 crancy-table__data-5">
                            <div class="crancy-table__actions">
                              <div class="crancy-table__status crancy-table__status--paid">
                                {% if notification.notification_type == "payment_success" %}
                                  Successful payment
                                {% elif notification.notification_type == "wallet_debit" %}
                                  Wallet debited
                                {% elif notification.notification_type == "WALLET_CREDIT" %}
                                  Wallet credited
                                {% else %}
                                  {{ notification.notification_type }}
                                {% endif %}
                              </div>
                            </div>
                          </td>
                          <td class="crancy-table__column-2 crancy-table__data-2">
                            <h4 class="crancy-table__product-title">{{ notification.created_at|date:"M d, Y" }}</h4>
                          </td>
                          <td class="crancy-table__column-3 crancy-table__data-3">
                            <h4 class="crancy-table__product-title">{{ notification.message }}</h4>
                          </td>
                        </tr>
                      {% endfor %}
                    </tbody>
                    <!-- Pagination Links -->
                    <div id="pagination">
                      {% if is_paginated %}
                        <nav>
                          <ul class="pagination">
                            {% if page_obj.has_previous %}
                              <li class="page-item">
                                <a class="page-link"
                                   href="?page={{ page_obj.previous_page_number }}"
                                   aria-label="Previous">
                                  <span aria-hidden="true">&laquo;</span>
                                </a>
                              </li>
                            {% endif %}
                            {% for num in paginator.page_range %}
                              <li class="page-item {% if num == page_obj.number %}active{% endif %}">
                                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                              </li>
                            {% endfor %}
                            {% if page_obj.has_next %}
                              <li class="page-item">
                                <a class="page-link"
                                   href="?page={{ page_obj.next_page_number }}"
                                   aria-label="Next">
                                  <span aria-hidden="true">&raquo;</span>
                                </a>
                              </li>
                            {% endif %}
                          </ul>
                        </nav>
                      {% endif %}
                    </div>
                    <!-- End crancy Table Body -->
                  </table>
                  <!-- End crancy Table -->
                {% endif %}
              </div>
            </div>
            <!-- End Dashboard Inner -->
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End crancy Dashboard -->
</div>
<!-- AJAX Script -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  // AJAX for Mark All as Read
  $("#mark-all-read").click(function() {
    $.ajax({
      url: "{% url 'referals:mark_all_notifications_read' %}",
      method: "POST",
      headers: {
        "X-CSRFToken": "{{ csrf_token }}"
      },
      success: function(response) {
        if (response.status === "success") {
          alert(response.message);
          // Update DOM
          $("#unread-count").text("0");
          $("span.badge.bg-warning").remove(); // Remove 'Unread' badges
        }
      },
      error: function() {
        alert("An error occurred. Please try again.");
      },
    });
  });
</script>
{% endblock content %}

acctmarket/templates/pages/refer/nowpaymentfund_wallet.html
{% extends 'dashboardbase.html' %}

{% load static %}

{% block content %}
  <!-- crancy Dashboard -->
  <section class="crancy-adashboard crancy-show">
    <div class="container container__bscreen">
      <div class="row">
        <div class="col-xxl-8 col-12 crancy-main__column">
          <div class="crancy-body">
            <!-- Dashboard Inner -->
            <div class="crancy-dsinner">
              <form method="post" action="{% url 'referals:fund_wallet' %}">
                {% csrf_token %}
                <div class="row">
                  <div class="container">
                    <div class="row justify-content-center">
                      <div class="col-lg-6 col-md-8 col-sm-10 col-12 mg-top-30">
                        <!-- Product Card -->
                        <div class="crancy-product-card">
                          <h4 class="crancy-product-card__title">
                            Fund Wallet with Crypto Currency
                            <a href="#">
                              <img src="{% static 'dashboard/img/alert-circle.svg' %}" alt="Info" />
                            </a>
                          </h4>
                          {% include 'partials/_messages.html' %}
                          <div class="crancy__item-form--group mg-top-25">
                            <label class="crancy__item-label crancy__item-label-product">Enter Amount</label>
                            {{ form.amount }}
                          </div>
                          <br />
                          <button type="submit" class="btn btn-outline-primary">Fund Wallet</button>
                        </div>
                        <!-- End Product Card -->
                      </div>
                    </div>
                  </div>
                </div>
              </form>
            </div>
            <!-- End Dashboard Inner -->
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End crancy Dashboard -->
</div>
{% endblock content %}