acctmarket/applications/blog/urls.py
from django.urls import path

from acctmarket.applications.blog import views

app_name = "blog"
urlpatterns = [
    path(
        "create-post", views.CreateBlogPostView.as_view(),
        name="create_post"
    ),
    path(
        "create-category", views.CreateBlogCategory.as_view(),
        name="create_category"
    ),
    path(
        "edit-category/<slug:slug>/",
        views.EditPostCategoryView.as_view(),
        name="edit_category",
    ),  # noqa
    path(
        "delete-category/<slug:slug>/",
        views.DeletePostCategoryView.as_view(),
        name="delete_category",
    ),
    path(
        "create-list", views.CategoryListView.as_view(),
        name="category_list"
    ),
    path(
        "blog-list", views.BlogListView.as_view(),
        name="blog_list"
    ),
    path(
        "edit-blog/<slug:slug>/", views.BlogEditView.as_view(),
        name="edit_blog"
    ),
    path(
        "delete-blog/<slug:slug>/",
        views.BlogDeleteView.as_view(),
        name="delete_blog",
    ),
    path("", views.BlogViews.as_view(), name="blog_views"),
    path(
        "blog-detail/<slug:slug>/",
        views.BlogDetailView.as_view(),
        name="blog_detail",
    ),
    path(
        "create-banner", views.BannerCreateView.as_view(),
        name="banner_create"
    ),
    path(
        "list-banner", views.BannerListView.as_view(),
        name="list_banner"
    ),
    path(
        "edit-banner/<slug:slug>/",
        views.BannerEditView.as_view(),
        name="edit_banner",
    ),
    path(
        "delete-banner/<slug:slug>/",
        views.BannerDeleteView.as_view(),
        name="delete_banner",
    ),
]

acctmarket/applications/ecommerce/urls.py
from django.urls import path

from acctmarket.applications.ecommerce import views

app_name = "ecommerce"
urlpatterns = [
    path(
        "add-product", views.AddProductView.as_view(),
        name="add_product"
    ),
    path(
        "add-category", views.AddCategoryView.as_view(),
        name="add_category"
    ),
    path(
        "list-category", views.ListCategoryView.as_view(),
        name="list_category"
    ),
    path(
        "edit-category/<slug:pk>/",
        views.EditCategoryView.as_view(),
        name="edit_category",
    ),
    path(
        "delete-category/<slug:pk>/",
        views.DeleteCategoryView.as_view(),
        name="delete_category",
    ),
    path(
        "list-product", views.ListProductView.as_view(),
        name="list_product"
    ),
    path(
        "edit-product/<slug:pk>/",
        views.EditProductView.as_view(),
        name="edit_product",
    ),
    path(
        "delete-product/<slug:pk>/",
        views.DeleteProductView.as_view(),
        name="delete_product",
    ),
    path(
        "product-detail/<slug:pk>/",
        views.ProductDetailView.as_view(),
        name="product_detail",
    ),
    path(
        "create-product-image",
        views.ProductImagesCreateView.as_view(),
        name="create_product_image",
    ),
    path(
        "list-product-image",
        views.ListProductImages.as_view(),
        name="list_product_images",
    ),
    path(
        "update-product-image/<slug:pk>/",
        views.UpdateProductImages.as_view(),
        name="update_product_image",
    ),
    path(
        "delete-product-image/<slug:pk>/",
        views.DeleteProductImages.as_view(),
        name="delete_product_image",
    ),
    path(
        "product/<slug:pk>/add-review/",
        views.AddReviewsView.as_view(),
        name="add_review",
    ),
    path(
        "add-to-cart/", views.AddToCartView.as_view(),
        name="add_to_cart"
    ),
    path("cart", views.CartListView.as_view(), name="cart_list"),
    path(
        "delete-from-cart",
        views.DeleteFromCartView.as_view(),
        name="delete_from_cart_list",
    ),
    path(
        "update-to-cart",
        views.UpdateCartView.as_view(),
        name="delete_from_cart_list",
    ),

    path(
        "checkout", views.CheckoutView.as_view(),
        name="checkout"
    ),
    path(
        "proceed-payment", views.ProceedPayment.as_view(),
        name="proceed_payment"
    ),
    path(
        "payment-complete/",
        views.PaymentCompleteView.as_view(),
        name="payment_complete",
    ),
    path(
        "payment-failed",
        views.PaymentFailedView.as_view(),
        name="payment_failed",
    ),
    path(
        "wish-lists",
        views.WishlistListView.as_view(),
        name="wishlists",
    ),
    path(
        "add-to-wishlist",
        views.AddToWishlistView.as_view(),
        name="add_to_wishlist",
    ),
    path(
        "verify-payment/<str:reference>/",
        views.VerifyPaymentView.as_view(),
        name="verify_payment",
    ),
    path(
        "initiate-payment/<slug:order_id>/",
        views.InitiatePaystackPaymentView.as_view(),
        name="initiate_payment",
    ),
    path(
        "initiate-flutterwave-payment/<slug:order_id>/",
        views.InitiateFlutterwavePaymentView.as_view(),
        name="initiate_flutterwave_payment"

    ),
    path(
        "handle-flutter-wave-payment",
        views.HandleFlutterwavePaymentView.as_view(),
        name="handle_flutterwave_payment"
    ),
    path(
        "purchased-product",
        views.PurchasedProductsView.as_view(),
        name="purchased_products",
    ),
    path(
        "create_nowpayment/<slug:order_id>/",
        views.NowPaymentView.as_view(),
        name="create_nowpayment",
    ),
    path(
        "verify/nowpayment/<str:reference>/",
        views.VerifyNowPaymentView.as_view(),
        name="verify_nowpayment"
    ),
    path(
        "done-payment/<slug:order_id>/",
        views.DonePaymentView.as_view(),
        name="done_payment"
    ),
    path("ipn/", views.IPNView.as_view(), name="ipn"),


    # https://www.acctmarket.com/ecommerce/webhooks/flutterwave/
    path(
        "webhooks/flutterwave/",
        views.FlutterwaveWebhookView.as_view(),
        name="flutterwave_webhook"
        ),
    path(
         "wallet-payment/", views.WalletPaymentView.as_view(),
         name="wallet_payment"
        ),
    path(
            "apply-coupon/", views.ApplyCouponView.as_view(),
            name="apply_coupon"
        ),

]

acctmarket/applications/home/urls.py
from django.urls import path

from acctmarket.applications.home import views

app_name = "homeapp"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("shop", views.ProductShopListView.as_view(), name="shop_list"),
    path(
        "products/<slug:category_slug>/",
        views.ProductsCategoryList.as_view(),
        name="category_list",
    ),
    path(
        "product/<str:pk>/",
        views.ProductShopDetailView.as_view(),
        name="product_detail",
    ),
    path(
        "product-tags/<slug:tag_slug>/",
        views.ProductTagsList.as_view(),
        name="tag_list",
    ),
    path("search", views.ProductSearchView.as_view(),
         name="search"),
    path(
        "filter-product/", views.ProductFilterView.as_view(),
        name="filter_product"
    ),
    path(
        "dashboard", views.DashboardView.as_view(),
        name="dashboard"
    ),
    path(
        "order-details/<int:pk>/", views.OrderDetails.as_view(),
        name="order_details"
    ),
    path(
        "term-policy", views.TermsPolicy.as_view(),
        name="termspolicy"
    ),
    path(
        "contact-us", views.ContactPage.as_view(),
        name="contact_us"
    ),
    path(
        "contact-success", views.ContactSuccessPage.as_view(),
        name="contact_success"
    )
]

acctmarket/applications/refer/urls.py
from django.urls import path

from acctmarket.applications.refer.views import (FlutterWalletFundView,
                                                 FlutterwaveCallbackView,
                                                 MarkAllNotificationsReadView,
                                                 NotificationListView,
                                                 NowPaymentCallbackView,
                                                 NowPaymentWalletFundView,
                                                 ReferralListView,
                                                 SMSCampaignCreateView,
                                                 SMSCampaignDetailView,
                                                 SMSCampaignListView,
                                                 SMSCampaignSendView,
                                                 SMSCampaignUpdateView,
                                                 WalletDetailView,
                                                 WalletFundingCancelView,
                                                 WalletFundingSuccessView,
                                                 WalletTrasactionListViews)

app_name = "referals"
urlpatterns = [
    path("", ReferralListView.as_view(), name="referals_list"),
    path(
        "my-wallet",
        WalletDetailView.as_view(), name="walet_detail"
    ),
    path(
        "fund-wallet/now-payment",
        NowPaymentWalletFundView.as_view(), name="fund_wallet"
    ),
    path(
        "fund-wallets/flutter-wave",
        FlutterWalletFundView.as_view(), name="fund_wallet2"
    ),
    path(
        "wallet/funding-callback/",
        FlutterwaveCallbackView.as_view(), name="flutterwave_callback"
    ),
    path(
        "wallet/nowpayment-callback",
        NowPaymentCallbackView.as_view(),
        name="nowpayment_callback"
    ),
    path(
        "funding-success/",
        WalletFundingSuccessView.as_view(), name="funding_success"
    ),
    path(
        "funding-cancel/",
        WalletFundingCancelView.as_view(), name="funding_cancel"
    ),
    path(
        "transactions/", WalletTrasactionListViews.as_view(),
        name="wallet_transaction_list"
    ),
    path(
        "notifications/", NotificationListView.as_view(),
        name="notifications"
    ),
    path(
        "notifications/mark-all-read/",
        MarkAllNotificationsReadView.as_view(),
        name="mark_all_notifications_read"
    ),
    path(
        "campaigns/", SMSCampaignListView.as_view(),
        name="sms_campaign_list"
    ),
    path(
        "campaigns/<int:pk>/", SMSCampaignDetailView.as_view(),
        name="sms_campaign_detail"
    ),
    path(
        "campaigns/create/", SMSCampaignCreateView.as_view(),
        name="sms_campaign_create"
    ),
    path(
        "campaigns/<int:pk>/update/", SMSCampaignUpdateView.as_view(),
        name="sms_campaign_update"
    ),
    path(
        "campaigns/<int:pk>/send/", SMSCampaignSendView.as_view(),
        name="sms_campaign_send"
    ),
]

config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/", include(
            "acctmarket.applications.users.urls", namespace="users"
        )
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    #  ecomercce manaement
    path(
        "ecommerce/",
        include(
            "acctmarket.applications.ecommerce.urls", namespace="ecommerce"
        ),
    ),
    # support management
    path(
        "support/",
        include("acctmarket.applications.support.urls", namespace="support"),
    ),
    path("blog/", include(
        "acctmarket.applications.blog.urls", namespace="blog")
    ),
    path("", include(
        "acctmarket.applications.home.urls", namespace="homeapp")
    ),
    # referal management
    path(
        "referal/", include(
            "acctmarket.applications.refer.urls", namespace="refer"
        )
    ),

    path("ckeditor/", include("ckeditor_uploader.urls")),

    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns  # noqa

acctmarket/applications/home/models.py
# Create your models here.

acctmarket/applications/blog/views.py
from django.db.models import Count
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from acctmarket.applications.blog.forms import (Banner, BannerForm,
                                                BlogCategory, BlogCategoryForm,
                                                Post, PostForm)
from acctmarket.utils.mixins import ContentManagerRequiredMixin

# Create your views here.


class SlugMixin:
    slug_field = "slug"
    slug_url_kwarg = "slug"

    def get_object(self, queryset=None):
        """
        Retrieves an object from the queryset based on the provided slug.

        Parameters:
            queryset (QuerySet, optional): The queryset to filter the objects.
            If not provided, the default queryset is used.

        Returns:
            object: The object with the matching slug.
            If no object is found, a Http404 exception is raised.
        """
        if queryset is None:
            queryset = self.get_queryset()
        slug = self.kwargs.get(self.slug_url_kwarg)
        queryset = queryset.filter(**{self.slug_field: slug})
        return get_object_or_404(queryset)


class CreateBlogCategory(ContentManagerRequiredMixin, CreateView):
    model = BlogCategory
    form_class = BlogCategoryForm
    template_name = "pages/blog/create_blog_category.html"
    success_url = reverse_lazy("blog:category_list")


class CategoryListView(ContentManagerRequiredMixin, ListView):
    model = BlogCategory
    template_name = "pages/blog/category_list.html"
    paginate_by = 10

    def get_queryset(self):
        return BlogCategory.objects.annotate(
            total_products=Count("post")).order_by(
                "-created_at",
        )


class EditPostCategoryView(
    ContentManagerRequiredMixin, SlugMixin, UpdateView
):
    model = BlogCategory
    form_class = BlogCategoryForm
    template_name = "pages/blog/create_blog_category.html"
    success_url = reverse_lazy("blog:category_list")


class DeletePostCategoryView(
    ContentManagerRequiredMixin, SlugMixin, DeleteView
):
    model = BlogCategory
    template_name = "pages/blog/confirm_delete.html"
    success_url = reverse_lazy("blog:category_list")


# =======================================  Blog Categories ends here


class CreateBlogPostView(ContentManagerRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = "pages/blog/create_blog_post.html"
    success_url = reverse_lazy("blog:blog_list")


class BlogListView(ContentManagerRequiredMixin, ListView):
    model = Post
    paginate_by = 10
    template_name = "pages/blog/blog_list.html"

    def get_queryset(self):
        return Post.objects.all().order_by("-created_at")


class BlogEditView(ContentManagerRequiredMixin, SlugMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = "pages/blog/create_blog_post.html"
    success_url = reverse_lazy("blog:blog_list")


class BlogDeleteView(ContentManagerRequiredMixin, SlugMixin, DeleteView):
    model = Post
    template_name = "pages/blog/delete_blog.html"
    success_url = reverse_lazy("blog:blog_list")


class BlogViews(ListView):
    model = Post
    template_name = "pages/blog/blog_views.html"
    context_object_name = "blog_posts"
    paginate_by = 5

    def get_queryset(self):
        return Post.objects.all().order_by("-created_at")


class BlogDetailView(DetailView):
    model = Post
    template_name = "pages/blog/blog_details.html"
    context_object_name = "blog_post"
    slug_field = "slug"
    slug_url_kwarg = "slug"


# =======================================  End if blog section


class BannerCreateView(ContentManagerRequiredMixin, CreateView):
    model = Banner
    form_class = BannerForm
    template_name = "pages/blog/create_home_banner.html"
    success_url = reverse_lazy("blog:list_banner")


class BannerEditView(ContentManagerRequiredMixin, SlugMixin, UpdateView):
    model = Banner
    form_class = BannerForm
    template_name = "pages/blog/create_home_banner.html"
    success_url = reverse_lazy("blog:list_banner")


class BannerDeleteView(ContentManagerRequiredMixin, SlugMixin, DeleteView):
    model = Banner
    template_name = "pages/blog/delete_banner.html"
    success_url = reverse_lazy("blog:list_banner")


class BannerListView(ContentManagerRequiredMixin, ListView):
    model = Banner
    paginate_by = 10
    template_name = "pages/blog/banner_list.html"
    context_object_name = "banners"

acctmarket/templates/pages/ecommerce/checkout.html
{% extends "base.html" %}

{% load static %}

{% block main %}
  {% block content %}
    {% include 'partials/_messages.html' %}
    <div class="shopping-cart-steps">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="cart-steps">
              <ul class="clearfix">
                <li class="active">
                  <div class="inner">
                    <span class="step">01</span> <span class="inner-step">Shopping Cart</span>
                  </div>
                </li>
                <li class="active">
                  <div class="inner">
                    <span class="step">02</span> <span class="inner-step">Checkout</span>
                  </div>
                </li>
                <li>
                  <div class="inner">
                    <span class="step">03</span> <span class="inner-step">Payment Completed</span>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--checkout-area start-->
    <div class="checkout-area mt-15">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            {% comment %} <p>Returning customer? <a href="#">Click here</a> to login</p> {% endcomment %}
          </div>
        </div>
        <div class="row mt-10">
          <div class="col-lg-8">
            <div class="billing-form">
              <h4>My Details</h4>
              <form action="#">
                <div class="row">
                  <div class="col-lg-3 align-items-center">
                    <label>COUNTRY *</label>
                  </div>
                  <div class="col-lg-9">{{ user_country }}</div>
                </div>
                <div class="row">
                  <div class="col-lg-3">
                    <label>Name*</label>
                  </div>
                  <div class="col-lg-9">{{ user_name }}</div>
                </div>
                {% comment %} <div class="row">
              <div class="col-lg-3">
                <label>COMPANY NAME</label>
              </div>
              <div class="col-lg-9">
                <input type="text" />
              </div>
            </div>
            <div class="row">
              <div class="col-lg-3">
                <label>ADDRESS *</label>
              </div>
              <div class="col-lg-9">
                <input type="text" placeholder="Street Address" />
                <input type="text" placeholder="Apartment, suite, unite ect (optinal)" class="mt-sm-30" />
              </div>
                </div> {% endcomment %}
                {% comment %} <div class="row">
              <div class="col-lg-3">
                <label>TOWN / CITY *</label>
              </div>
              <div class="col-lg-9">
                <input type="text" />
              </div>
                </div> {% endcomment %}
                {% comment %} <div class="row">
              <div class="col-lg-3">
                <label>COUNTRY / STATES</label>
              </div>
              <div class="col-lg-9">
                <input type="text" />
              </div>
                </div> {% endcomment %}
                <div class="row">
                  <div class="col-lg-3">
                    <label>Wallet/Balance*</label>
                  </div>
                  <div class="col-lg-9">
                    {% comment %} <input type="text" /> {% endcomment %}
                    {{ wallet_balance }}
                  </div>
                </div>
                <div class="row">
                  <div class="col-lg-3">
                    <label>EMAIL ADDRESS *</label>
                  </div>
                  <div class="col-lg-9">{{ user_email }}</div>
                </div>
                <div class="row">
                  <div class="col-lg-3">
                    <label>PHONE *</label>
                  </div>
                  <div class="col-lg-9">{{ user_phone }}</div>
                </div>
                <div class="row">
                  <div class="col-lg-3">
                    <label>Order ID *</label>
                  </div>
                  <div class="col-lg-9">{{ order_id }}</div>
                </div>
                <div class="row">
                  <div class="col-lg-3">
                    <label>Payment ID  *</label>
                  </div>
                  <div class="col-lg-9">{{ payment_id }}</div>
                </div>
                {% comment %} <div class="row">
              <div class="col-lg-12">
                <p>Create an account by entering the information below. If you are a returning customer please login
                  at the top of the page</p>
              </div>
                </div> {% endcomment %}
                {% comment %} <div class="row">
              <div class="col-lg-3">
                <label>ACCOUNT PASSWORD *</label>
              </div>
              <div class="col-lg-9">
                <input type="text" />
              </div>
                </div> {% endcomment %}
                {% comment %} <div class="row">
              <div class="col-lg-3">
                <label class="p-0">ORDER NOTES</label>
              </div>
              <div class="col-lg-9">
                <input type="text" class="p-0" />
              </div>
                </div> {% endcomment %}
              </form>
            </div>
          </div>
          <div class="col-lg-4">
            {% if coupon_message %}
              <div class="alert alert-success">{{ coupon_message }}</div>
            {% endif %}
            {% if show_coupon_form %}
              <div class="sidebar-checkout">
                <div class="cart-box cart-coupon fix">
                  <h5>Promotrional Code</h5>
                  <div class="cart-box-inner">
                    <form method="post" action="{% url 'ecommerce:apply_coupon' %}">
                      {% csrf_token %}
                      <p>Enter your coupon if you have one</p>
                      <input type="text" name="coupon_code" id="coupon_code" />
                      <button href="#" class="btn-common">Apply</button>
                    </form>
                  </div>
                </div>
              </div>
            {% endif %}
            <div class="order-details mt-30">
              <h4>My Order</h4>
              <div class="order-details-inner">
                <table>
                  <thead>
                    <tr>
                      <th>PRODUCT</th>
                      <th>TOTAL</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for product_id, item in cart_data.items %}
                      <tr>
                        <td>
                          <img height="35" src="{{ item.image }}" alt="" />
                          {{ item.title|truncatechars:15 }}
                        </td>
                        <td>
                          <strong>${% widthratio item.price 1 item.quantity %}</strong>
                        </td>
                      </tr>
                    {% endfor %}
                    <td>ORDER TOTAL</td>
                    <td>
                      <strong>${{ cart_total_amount }}</strong>
                    </td>
                    <br />
                    <tr>
                      <td>Discount</td>
                      <td>
                        <strong>${{ discount }}</strong>
                      </td>
                    </tr>
                  </tr>
                </tbody>
              </table>
              <div class="payment-gateways mt-30">
                {% comment %} <div class="single-payment-gateway">
                <input type="checkbox" id="system1" />
                <label for="system1">Create an account?</label>
                <div class="payment-gateway-desc">
                  <p>Lorem ipsum dolor sit amet, consectetur adip elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua.</p>
                </div>
                </div> {% endcomment %}
                {% comment %} <div class="single-payment-gateway">
                <input type="radio" id="system2" />
                <label for="system2">Cheque Payment</label>
                </div> {% endcomment %}
                {% comment %} <div class="single-payment-gateway">
                <input type="radio" id="system3" />
                <label for="system3">Paypal</label>
                </div> {% endcomment %}
              </div>
              {% comment %} <form id="paymentForm"> {% endcomment %}
              <div class="form-group">
                {% comment %} <label for="email">Email Address</label> {% endcomment %}
                <input type="hidden" id="email-address" value="{{ user_email }}" required />
              </div>
              <div class="form-group">
                {% comment %} <label for="amount">Amount</label> {% endcomment %}
                <input type="hidden" id="amount" value="{{ order_price }}" required />
              </div>
              <div class="form-group">
                {% comment %} <label for="first-name">First Name</label> {% endcomment %}
                <input type="hidden" id="first-name" value="{{ user_name }}" />
              </div>
              <div class="form-group">
                {% comment %} <label for="last-name">Last Name</label> {% endcomment %}
                {% comment %} <input type="text" id="last-name" /> {% endcomment %}
              </div>
              <form method="post">
                {% csrf_token %}
                {% comment %} <input type="hidden" name="order_id" value="{{ order.id }}" />
                <div class="place-order text-center mt-60">
                  <a href="{% url 'ecommerce:proceed_payment' %}" type="submit" class="btn-common width-180">Pay With
                    Paystack</a>
                </div> {% endcomment %}
                {% comment %} <div class="place-order text-center mt-60">
                  <a href="{% url 'ecommerce:proceed_payment' %}" type="submit" class="btn-common width-180">Pay with
                    Naira</a>
                </div>
                <div class="place-order text-center mt-1">
                  <form action="{% url 'ecommerce:create_nowpayment' order_id=order_id  %}" method="get">

                    <a href="{% url 'ecommerce:create_nowpayment' order_id=order_id %}" class="btn-common width-180">Pay
                      with Crypto</a>
                </form> {% endcomment %}
                {% if not can_pay_with_wallet %}
                  <p class="text-danger">Insufficient balance. Please add funds to your wallet.</p>
                  <a href="{% url 'referals:walet_detail' %}"
                     type="submit"
                     class="btn-common width-180">Add Funds</a>
                {% else %}
                  <div class="place-order text-center mt-60">
                    <a href="{% url 'ecommerce:wallet_payment' %}"
                       class="btn-common width-180">Proceed to Pay with Wallet</a>
                  </div>
                {% endif %}
              </div>
              {% comment %}
              </form> {% endcomment %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--checkout-area end-->
  <!--brands-area start-->
  {% comment %} <div class="container mt-20">
  <div class="brands-area br-none">
    <div class="row">
      <div class="col-lg-12">
        <div class="brand-items">
          <div class="brand-item">
            <a href="#">
              <img class="brand-static" src="assets/images/brands/1.jpg" alt="" />
            </a>
          </div>
          <div class="brand-item">
            <a href="#">
              <img class="brand-static" src="assets/images/brands/2.jpg" alt="" />
            </a>
          </div>
          <div class="brand-item">
            <a href="#">
              <img class="brand-static" src="assets/images/brands/3.jpg" alt="" />
            </a>
          </div>
          <div class="brand-item">
            <a href="#">
              <img class="brand-static" src="assets/images/brands/4.jpg" alt="" />
            </a>
          </div>
          <div class="brand-item">
            <a href="#">
              <img class="brand-static" src="assets/images/brands/5.jpg" alt="" />
            </a>
          </div>
          <div class="brand-item">
            <a href="#">
              <img class="brand-static" src="assets/images/brands/6.jpg" alt="" />
            </a>
          </div>
          <div class="brand-item">
            <a href="#">
              <img class="brand-static" src="assets/images/brands/7.jpg" alt="" />
            </a>
          </div>
          <div class="brand-item">
            <a href="#">
              <img class="brand-static" src="assets/images/brands/8.jpg" alt="" />
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>

  </div> {% endcomment %}
  <script src="https://js.paystack.co/v1/inline.js"></script>
  <script>
    function makePaystackPayment() {
      let ref = "{{ payment.reference }}";
      let obj = {
        key: "{{ paystack_public_key }}",
        email: "{{ user_email }}",
        amount: "{{ payment.amount_value }}",
        ref: ref,
        onClose: function() {
          alert('Window closed.');
        }
      };

      var handler = PaystackPop.setup(obj);
      handler.openIframe();
    }
  </script>
  <br />
  <br />
{% endblock content %}
{% endblock main %}