acctmarket/applications/blog/urls.py
from django.urls import path

from acctmarket.applications.blog import views

app_name = "blog"
urlpatterns = [
    path(
        "create-post", views.CreateBlogPostView.as_view(),
        name="create_post"
    ),
    path(
        "create-category", views.CreateBlogCategory.as_view(),
        name="create_category"
    ),
    path(
        "edit-category/<slug:slug>/",
        views.EditPostCategoryView.as_view(),
        name="edit_category",
    ),  # noqa
    path(
        "delete-category/<slug:slug>/",
        views.DeletePostCategoryView.as_view(),
        name="delete_category",
    ),
    path(
        "create-list", views.CategoryListView.as_view(),
        name="category_list"
    ),
    path(
        "blog-list", views.BlogListView.as_view(),
        name="blog_list"
    ),
    path(
        "edit-blog/<slug:slug>/", views.BlogEditView.as_view(),
        name="edit_blog"
    ),
    path(
        "delete-blog/<slug:slug>/",
        views.BlogDeleteView.as_view(),
        name="delete_blog",
    ),
    path("", views.BlogViews.as_view(), name="blog_views"),
    path(
        "blog-detail/<slug:slug>/",
        views.BlogDetailView.as_view(),
        name="blog_detail",
    ),
    path(
        "create-banner", views.BannerCreateView.as_view(),
        name="banner_create"
    ),
    path(
        "list-banner", views.BannerListView.as_view(),
        name="list_banner"
    ),
    path(
        "edit-banner/<slug:slug>/",
        views.BannerEditView.as_view(),
        name="edit_banner",
    ),
    path(
        "delete-banner/<slug:slug>/",
        views.BannerDeleteView.as_view(),
        name="delete_banner",
    ),
]

acctmarket/applications/ecommerce/urls.py
from django.urls import path

from acctmarket.applications.ecommerce import views

app_name = "ecommerce"
urlpatterns = [
    path(
        "add-product", views.AddProductView.as_view(),
        name="add_product"
    ),
    path(
        "add-category", views.AddCategoryView.as_view(),
        name="add_category"
    ),
    path(
        "list-category", views.ListCategoryView.as_view(),
        name="list_category"
    ),
    path(
        "edit-category/<slug:pk>/",
        views.EditCategoryView.as_view(),
        name="edit_category",
    ),
    path(
        "delete-category/<slug:pk>/",
        views.DeleteCategoryView.as_view(),
        name="delete_category",
    ),
    path(
        "list-product", views.ListProductView.as_view(),
        name="list_product"
    ),
    path(
        "edit-product/<slug:pk>/",
        views.EditProductView.as_view(),
        name="edit_product",
    ),
    path(
        "delete-product/<slug:pk>/",
        views.DeleteProductView.as_view(),
        name="delete_product",
    ),
    path(
        "product-detail/<slug:pk>/",
        views.ProductDetailView.as_view(),
        name="product_detail",
    ),
    path(
        "create-product-image",
        views.ProductImagesCreateView.as_view(),
        name="create_product_image",
    ),
    path(
        "list-product-image",
        views.ListProductImages.as_view(),
        name="list_product_images",
    ),
    path(
        "update-product-image/<slug:pk>/",
        views.UpdateProductImages.as_view(),
        name="update_product_image",
    ),
    path(
        "delete-product-image/<slug:pk>/",
        views.DeleteProductImages.as_view(),
        name="delete_product_image",
    ),
    path(
        "product/<slug:pk>/add-review/",
        views.AddReviewsView.as_view(),
        name="add_review",
    ),
    path(
        "add-to-cart/", views.AddToCartView.as_view(),
        name="add_to_cart"
    ),
    path("cart", views.CartListView.as_view(), name="cart_list"),
    path(
        "delete-from-cart",
        views.DeleteFromCartView.as_view(),
        name="delete_from_cart_list",
    ),
    path(
        "update-to-cart",
        views.UpdateCartView.as_view(),
        name="delete_from_cart_list",
    ),

    path(
        "checkout", views.CheckoutView.as_view(),
        name="checkout"
    ),
    path(
        "proceed-payment", views.ProceedPayment.as_view(),
        name="proceed_payment"
    ),
    path(
        "payment-complete/",
        views.PaymentCompleteView.as_view(),
        name="payment_complete",
    ),
    path(
        "payment-failed",
        views.PaymentFailedView.as_view(),
        name="payment_failed",
    ),
    path(
        "wish-lists",
        views.WishlistListView.as_view(),
        name="wishlists",
    ),
    path(
        "add-to-wishlist",
        views.AddToWishlistView.as_view(),
        name="add_to_wishlist",
    ),
    path(
        "verify-payment/<str:reference>/",
        views.VerifyPaymentView.as_view(),
        name="verify_payment",
    ),
    path(
        "initiate-payment/<slug:order_id>/",
        views.InitiatePaystackPaymentView.as_view(),
        name="initiate_payment",
    ),
    path(
        "initiate-flutterwave-payment/<slug:order_id>/",
        views.InitiateFlutterwavePaymentView.as_view(),
        name="initiate_flutterwave_payment"

    ),
    path(
        "handle-flutter-wave-payment",
        views.HandleFlutterwavePaymentView.as_view(),
        name="handle_flutterwave_payment"
    ),
    path(
        "purchased-product",
        views.PurchasedProductsView.as_view(),
        name="purchased_products",
    ),
    path(
        "create_nowpayment/<slug:order_id>/",
        views.NowPaymentView.as_view(),
        name="create_nowpayment",
    ),
    path(
        "verify/nowpayment/<str:reference>/",
        views.VerifyNowPaymentView.as_view(),
        name="verify_nowpayment"
    ),
    path(
        "done-payment/<slug:order_id>/",
        views.DonePaymentView.as_view(),
        name="done_payment"
    ),
    path("ipn/", views.IPNView.as_view(), name="ipn"),


    # https://www.acctmarket.com/ecommerce/webhooks/flutterwave/
    path(
        "webhooks/flutterwave/",
        views.FlutterwaveWebhookView.as_view(),
        name="flutterwave_webhook"
        ),
    path(
         "wallet-payment/", views.WalletPaymentView.as_view(),
         name="wallet_payment"
        ),
    path(
            "apply-coupon/", views.ApplyCouponView.as_view(),
            name="apply_coupon"
        ),

]

acctmarket/applications/home/urls.py
from django.urls import path

from acctmarket.applications.home import views

app_name = "homeapp"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("shop", views.ProductShopListView.as_view(), name="shop_list"),
    path(
        "products/<slug:category_slug>/",
        views.ProductsCategoryList.as_view(),
        name="category_list",
    ),
    path(
        "product/<str:pk>/",
        views.ProductShopDetailView.as_view(),
        name="product_detail",
    ),
    path(
        "product-tags/<slug:tag_slug>/",
        views.ProductTagsList.as_view(),
        name="tag_list",
    ),
    path("search", views.ProductSearchView.as_view(),
         name="search"),
    path(
        "filter-product/", views.ProductFilterView.as_view(),
        name="filter_product"
    ),
    path(
        "dashboard", views.DashboardView.as_view(),
        name="dashboard"
    ),
    path(
        "order-details/<int:pk>/", views.OrderDetails.as_view(),
        name="order_details"
    ),
    path(
        "term-policy", views.TermsPolicy.as_view(),
        name="termspolicy"
    ),
    path(
        "contact-us", views.ContactPage.as_view(),
        name="contact_us"
    ),
    path(
        "contact-success", views.ContactSuccessPage.as_view(),
        name="contact_success"
    )
]

acctmarket/applications/refer/urls.py
from django.urls import path

from acctmarket.applications.refer.views import (FlutterWalletFundView,
                                                 FlutterwaveCallbackView,
                                                 MarkAllNotificationsReadView,
                                                 NotificationListView,
                                                 NowPaymentCallbackView,
                                                 NowPaymentWalletFundView,
                                                 ReferralListView,
                                                 SMSCampaignCreateView,
                                                 SMSCampaignDetailView,
                                                 SMSCampaignListView,
                                                 SMSCampaignSendView,
                                                 SMSCampaignUpdateView,
                                                 WalletDetailView,
                                                 WalletFundingCancelView,
                                                 WalletFundingSuccessView,
                                                 WalletTrasactionListViews)

app_name = "referals"
urlpatterns = [
    path("", ReferralListView.as_view(), name="referals_list"),
    path(
        "my-wallet",
        WalletDetailView.as_view(), name="walet_detail"
    ),
    path(
        "fund-wallet/now-payment",
        NowPaymentWalletFundView.as_view(), name="fund_wallet"
    ),
    path(
        "fund-wallets/flutter-wave",
        FlutterWalletFundView.as_view(), name="fund_wallet2"
    ),
    path(
        "wallet/funding-callback/",
        FlutterwaveCallbackView.as_view(), name="flutterwave_callback"
    ),
    path(
        "wallet/nowpayment-callback",
        NowPaymentCallbackView.as_view(),
        name="nowpayment_callback"
    ),
    path(
        "funding-success/",
        WalletFundingSuccessView.as_view(), name="funding_success"
    ),
    path(
        "funding-cancel/",
        WalletFundingCancelView.as_view(), name="funding_cancel"
    ),
    path(
        "transactions/", WalletTrasactionListViews.as_view(),
        name="wallet_transaction_list"
    ),
    path(
        "notifications/", NotificationListView.as_view(),
        name="notifications"
    ),
    path(
        "notifications/mark-all-read/",
        MarkAllNotificationsReadView.as_view(),
        name="mark_all_notifications_read"
    ),
    path(
        "campaigns/", SMSCampaignListView.as_view(),
        name="sms_campaign_list"
    ),
    path(
        "campaigns/<int:pk>/", SMSCampaignDetailView.as_view(),
        name="sms_campaign_detail"
    ),
    path(
        "campaigns/create/", SMSCampaignCreateView.as_view(),
        name="sms_campaign_create"
    ),
    path(
        "campaigns/<int:pk>/update/", SMSCampaignUpdateView.as_view(),
        name="sms_campaign_update"
    ),
    path(
        "campaigns/<int:pk>/send/", SMSCampaignSendView.as_view(),
        name="sms_campaign_send"
    ),
]

config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/", include(
            "acctmarket.applications.users.urls", namespace="users"
        )
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    #  ecomercce manaement
    path(
        "ecommerce/",
        include(
            "acctmarket.applications.ecommerce.urls", namespace="ecommerce"
        ),
    ),
    # support management
    path(
        "support/",
        include("acctmarket.applications.support.urls", namespace="support"),
    ),
    path("blog/", include(
        "acctmarket.applications.blog.urls", namespace="blog")
    ),
    path("", include(
        "acctmarket.applications.home.urls", namespace="homeapp")
    ),
    # referal management
    path(
        "referal/", include(
            "acctmarket.applications.refer.urls", namespace="refer"
        )
    ),

    path("ckeditor/", include("ckeditor_uploader.urls")),

    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns  # noqa

acctmarket/applications/home/models.py
# Create your models here.

acctmarket/applications/blog/views.py
from django.db.models import Count
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from acctmarket.applications.blog.forms import (Banner, BannerForm,
                                                BlogCategory, BlogCategoryForm,
                                                Post, PostForm)
from acctmarket.utils.mixins import ContentManagerRequiredMixin

# Create your views here.


class SlugMixin:
    slug_field = "slug"
    slug_url_kwarg = "slug"

    def get_object(self, queryset=None):
        """
        Retrieves an object from the queryset based on the provided slug.

        Parameters:
            queryset (QuerySet, optional): The queryset to filter the objects.
            If not provided, the default queryset is used.

        Returns:
            object: The object with the matching slug.
            If no object is found, a Http404 exception is raised.
        """
        if queryset is None:
            queryset = self.get_queryset()
        slug = self.kwargs.get(self.slug_url_kwarg)
        queryset = queryset.filter(**{self.slug_field: slug})
        return get_object_or_404(queryset)


class CreateBlogCategory(ContentManagerRequiredMixin, CreateView):
    model = BlogCategory
    form_class = BlogCategoryForm
    template_name = "pages/blog/create_blog_category.html"
    success_url = reverse_lazy("blog:category_list")


class CategoryListView(ContentManagerRequiredMixin, ListView):
    model = BlogCategory
    template_name = "pages/blog/category_list.html"
    paginate_by = 10

    def get_queryset(self):
        return BlogCategory.objects.annotate(
            total_products=Count("post")).order_by(
                "-created_at",
        )


class EditPostCategoryView(
    ContentManagerRequiredMixin, SlugMixin, UpdateView
):
    model = BlogCategory
    form_class = BlogCategoryForm
    template_name = "pages/blog/create_blog_category.html"
    success_url = reverse_lazy("blog:category_list")


class DeletePostCategoryView(
    ContentManagerRequiredMixin, SlugMixin, DeleteView
):
    model = BlogCategory
    template_name = "pages/blog/confirm_delete.html"
    success_url = reverse_lazy("blog:category_list")


# =======================================  Blog Categories ends here


class CreateBlogPostView(ContentManagerRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = "pages/blog/create_blog_post.html"
    success_url = reverse_lazy("blog:blog_list")


class BlogListView(ContentManagerRequiredMixin, ListView):
    model = Post
    paginate_by = 10
    template_name = "pages/blog/blog_list.html"

    def get_queryset(self):
        return Post.objects.all().order_by("-created_at")


class BlogEditView(ContentManagerRequiredMixin, SlugMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = "pages/blog/create_blog_post.html"
    success_url = reverse_lazy("blog:blog_list")


class BlogDeleteView(ContentManagerRequiredMixin, SlugMixin, DeleteView):
    model = Post
    template_name = "pages/blog/delete_blog.html"
    success_url = reverse_lazy("blog:blog_list")


class BlogViews(ListView):
    model = Post
    template_name = "pages/blog/blog_views.html"
    context_object_name = "blog_posts"
    paginate_by = 5

    def get_queryset(self):
        return Post.objects.all().order_by("-created_at")


class BlogDetailView(DetailView):
    model = Post
    template_name = "pages/blog/blog_details.html"
    context_object_name = "blog_post"
    slug_field = "slug"
    slug_url_kwarg = "slug"


# =======================================  End if blog section


class BannerCreateView(ContentManagerRequiredMixin, CreateView):
    model = Banner
    form_class = BannerForm
    template_name = "pages/blog/create_home_banner.html"
    success_url = reverse_lazy("blog:list_banner")


class BannerEditView(ContentManagerRequiredMixin, SlugMixin, UpdateView):
    model = Banner
    form_class = BannerForm
    template_name = "pages/blog/create_home_banner.html"
    success_url = reverse_lazy("blog:list_banner")


class BannerDeleteView(ContentManagerRequiredMixin, SlugMixin, DeleteView):
    model = Banner
    template_name = "pages/blog/delete_banner.html"
    success_url = reverse_lazy("blog:list_banner")


class BannerListView(ContentManagerRequiredMixin, ListView):
    model = Banner
    paginate_by = 10
    template_name = "pages/blog/banner_list.html"
    context_object_name = "banners"

acctmarket/templates/pages/blog/banner_list.html
{% extends 'dashboard_base.html' %}

{% load static %}

{% block content %}
  <!-- main-content -->
  <div class="main-content">
    <!-- main-content-wrap -->
    <div class="main-content-inner">
      <!-- main-content-wrap -->
      <div class="main-content-wrap">
        <div class="flex items-center flex-wrap justify-between gap20 mb-27">
          <h3>All banner</h3>
          <ul class="breadcrumbs flex items-center flex-wrap justify-start gap10">
            <li>
              <a href="index.html">
                <div class="text-tiny">Dashboard</div>
              </a>
            </li>
            <li>
              <i class="icon-chevron-right"></i>
            </li>
            <li>
              <a href="#">
                <div class="text-tiny">banner</div>
              </a>
            </li>
            <li>
              <i class="icon-chevron-right"></i>
            </li>
            <li>
              <div class="text-tiny">All banner</div>
            </li>
          </ul>
        </div>
        <!-- all-banner -->
        <div class="wg-box">
          <div class="flex items-center justify-between gap10 flex-wrap">
            <div class="wg-filter flex-grow">
              <div class="show">
                <div class="text-tiny">Showing</div>
                <div class="select">
                  <select class="">
                    <option>10</option>
                    <option>20</option>
                    <option>30</option>
                  </select>
                </div>
                <div class="text-tiny">entries</div>
              </div>
              <form class="form-search">
                <fieldset class="name">
                  <input type="text"
                         placeholder="Search here..."
                         class=""
                         name="name"
                         tabindex="2"
                         value=""
                         aria-required="true"
                         required="" />
                </fieldset>
                <div class="button-submit">
                  <button class="" type="submit">
                    <i class="icon-search"></i>
                  </button>
                </div>
              </form>
            </div>
            <a class="tf-button style-1 w208" href="{% url 'blog:banner_create' %}"><i class="icon-plus"></i>Add new</a>
          </div>
          <div class="wg-table table-all-banner">
            <ul class="table-title flex gap20 mb-14">
              <li>
                <div class="body-title">Banner</div>
              </li>
              <li>
                <div class="body-title">Category</div>
              </li>
              <li>
                <div class="body-title">Price</div>
              </li>
              <li>
                <div class="body-title">Start date</div>
              </li>
              <li>
                <div class="body-title">Action</div>
              </li>
            </ul>
            <ul class="flex flex-column">
              {% for banner in banners %}
                <li class="product-item gap14">
                  <div class="image no-bg">
                    <img src="{{ banner.image.url }}" alt="" />
                  </div>
                  <div class="flex items-center justify-between gap20 flex-grow">
                    <div class="name">
                      <a href="product-list.html" class="body-title-2">{{ banner.title }}</a>
                    </div>
                    {% comment %} <div class="body-text">
                      {% if cats.total_products %}
                        ({{ cats.total_products }})
                      {% else %}
                        (0)
                      {% endif %}
                    </div> {% endcomment %}
                    <div class="body-text">{{ banner.category }}</div>
                    <div class="body-text">{{ banner.price }}</div>
                    <div class="body-text">{{ banner.created_at|date:"Y-m" }}</div>
                    <div class="list-icon-function">
                      <div class="item eye">
                        <i class="icon-eye"></i>
                      </div>
                      <a href="{% url 'blog:edit_banner' banner.slug %}" class="item edit">
                        <i class="icon-edit-3"></i>
                      </a>
                      <a href="{% url 'blog:delete_banner' banner.slug %}" class="item trash">
                        <i class="icon-trash-2"></i>
                      </a>
                    </div>
                  </div>
                </li>
              {% endfor %}
            </ul>
          </div>
          <div class="divider"></div>
          <!-- Pagination -->
          <div class="divider"></div>
          <div class="flex items-center justify-between flex-wrap gap10">
            <div class="text-tiny">
              Showing {{ page_obj.start_index }}-{{ page_obj.end_index }} of {{ page_obj.paginator.count }} entries
            </div>
            <ul class="wg-pagination">
              {% if page_obj.has_previous %}
                <li>
                  <a href="?page=1"><i class="icon-chevron-left"></i></a>
                </li>
              {% endif %}
              {% for num in page_obj.paginator.page_range %}
                {% if num == page_obj.number %}
                  <li class="active">
                    <a href="#">{{ num }}</a>
                  </li>
                {% else %}
                  <li>
                    <a href="?page={{ num }}">{{ num }}</a>
                  </li>
                {% endif %}
              {% endfor %}
              {% if page_obj.has_next %}
                <li>
                  <a href="?page={{ page_obj.paginator.num_pages }}"><i class="icon-chevron-right"></i></a>
                </li>
              {% endif %}
            </ul>
          </div>
          <!-- End Pagination -->
        </div>
        <!-- /all-banner -->
      </div>
      <!-- /main-content-wrap -->
    </div>
    <!-- /main-content-wrap -->
  {% endblock content %}

acctmarket/templates/pages/blog/blog_views.html
{% extends "base.html" %}

{% load static %}

{% block main %}
  {% block content %}
    {% include 'partials/_messages.html' %}
    {% include 'partials/_sidebar.html' %}
    <!--products-area start-->
    <div class="shop-area">
      <div class="container">
        <div class="row">
          <div class="col-lg-3">{% include 'partials/_blog_sidebar.html' %}</div>
          <div class="col-lg-9">
            {% for blog in blog_posts %}
              <div class="single-blog mt-30">
                <div class="row">
                  <div class="col-lg-6">
                    <div class="blog-thumb">
                      <a href="{% url 'blog:blog_detail' blog.slug %}">
                        <img src="{{ blog.image.url }}" alt="" />
                      </a>
                    </div>
                  </div>
                  <div class="col-lg-6">
                    <div class="blog-desc">
                      <a href="#" class="catlink">{{ blog.category }}</a>
                      <h2>
                        <a href="{% url 'blog:blog_detail' blog.slug %}">{{ blog.title }}</a>
                      </h2>
                      <div class="blog-meta">
                        <ul class="list-none">
                          <li>
                            <a href="#">{{ blog.created_at|date:" M d Y" }}</a>
                          </li>
                          <li>
                            <span>|</span>
                          </li>
                          {% comment %} <li><a href="#">3 Comments</a></li> {% endcomment %}
                        </ul>
                      </div>
                      <p>{{ blog.content|safe|truncatechars:100 }}</p>
                      <a href="{% url 'blog:blog_detail' blog.slug %}" class="btn-common">Read More <i class="fa fa-angle-double-right"></i></a>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
        {% include 'partials/_shop_pagianations.html' %}
      </div>
    </div>
    <!--products-area end-->
    <!--brands-area start-->
    <div class="container mt-60">
      <div class="brands-area">
        <div class="row">
          <div class="col-lg-12">
            <div class="brand-items">
              <div class="brand-item">
                <a href="#">
                  <img class="brand-static"
                       src="{% static 'assets/images/brands/1.jpg' %}"
                       alt="" />
                </a>
              </div>
              <div class="brand-item">
                <a href="#">
                  <img class="brand-static"
                       src="{% static 'assets/images/brands/2.jpg' %}"
                       alt="" />
                </a>
              </div>
              <div class="brand-item">
                <a href="#">
                  <img class="brand-static"
                       src="{% static 'assets/images/brands/3.jpg' %}"
                       alt="" />
                </a>
              </div>
              <div class="brand-item">
                <a href="#">
                  <img class="brand-static"
                       src="{% static 'assets/images/brands/4.jpg' %}"
                       alt="" />
                </a>
              </div>
              <div class="brand-item">
                <a href="#">
                  <img class="brand-static"
                       src="{% static 'assets/images/brands/5.jpg' %}"
                       alt="" />
                </a>
              </div>
              <div class="brand-item">
                <a href="#">
                  <img class="brand-static"
                       src="{% static 'assets/images/brands/6.jpg' %}"
                       alt="" />
                </a>
              </div>
              <div class="brand-item">
                <a href="#">
                  <img class="brand-static"
                       src="{% static 'assets/images/brands/7.jpg' %}"
                       alt="" />
                </a>
              </div>
              <div class="brand-item">
                <a href="#">
                  <img class="brand-static"
                       src="{% static 'assets/images/brands/8.jpg' %}"
                       alt="" />
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--brands-area end-->
  {% endblock content %}
{% endblock main %}

acctmarket/templates/pages/blog/confirm_delete.html
{% extends 'dashboardbase.html' %}

{% load static %}

{% block content %}
  <!-- main-content -->
  <div class="main-content">
    <!-- main-content-wrap -->
    <div class="main-content-inner">
      <!-- main-content-wrap -->
      <div class="main-content-wrap">
        <div class="flex items-center flex-wrap justify-between gap20 mb-27">
          <h3>category infomation</h3>
          <ul class="breadcrumbs flex items-center flex-wrap justify-start gap10">
            <li>
              <a href="#">
                <div class="text-tiny">Dashboard</div>
              </a>
            </li>
            <li>
              <i class="icon-chevron-right"></i>
            </li>
            <li>
              <a href="#">
                <div class="text-tiny">category</div>
              </a>
            </li>
            <li>
              <i class="icon-chevron-right"></i>
            </li>
            <li>
              <div class="text-tiny">delete category</div>
            </li>
          </ul>
        </div>
        <!-- delete-category -->
        <div class="wg-box">
          <form method="POST"
                class="form-delete-product form-style-1"
                enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="name">
              <h5>Are you sure you want to delete the category "{{ object.title }}"?</h5>
            </fieldset>
          </fieldset>
          <div class="bot">
            <div></div>
            <button class="tf-button w208" type="submit">Delete</button>
            <a href="{% url 'ecommerce:list_category' %}" class="tf-button w208">Cancel</a>
          </div>
        </form>
      </div>
      <!-- /delete-category -->
    </div>
    <!-- /main-content-wrap -->
  </div>
  <!-- /main-content-wrap -->
  <!-- bottom-page -->
{% endblock content %}